name: Multiple Jobs

on: push

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Building Project"

  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Testing Project"
